name: simubank
description: "Home assignment for Kibit Solutions interview."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Architecture, State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Network client
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # Local storage
  shared_preferences: 2.3.3

  # Serialization
  freezed_annotation: ^2.4.4
  json_serializable: 6.9.0

  # Navigation
  auto_route: ^9.3.0+1

  # UI
  infinite_scroll_pagination: 4.1.0
  currency_formatter: 2.2.2

  # Localization
  easy_localization: ^3.0.7

  # Utils
  package_info_plus: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  riverpod_generator: ^2.6.3

flutter_gen:
  output: lib/generated/

flutter:
  assets:
    - assets/images/
    - assets/translations/
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
  uses-material-design: true